Repository KevinGlitch/crystall-punk-14, pull requests merged in 2025-05, with the labels that each got.

#2 Update CP14SkillStorageComponent.cs
  Content.Shared/_CP14/Skill/Components/CP14SkillStorageComponent.cs
Labels: enhancement

#3 Spell cooldown changes
  Resources/Prototypes/_CP14/Entities/Actions/Spells/Dimension/T1_shadow_swap.yml
  Resources/Prototypes/_CP14/Entities/Actions/Spells/Dimension/T2_shadow_step.yml
  Resources/Prototypes/_CP14/Entities/Actions/Spells/Fire/fireball.yml
  Resources/Prototypes/_CP14/Entities/Actions/Spells/Fire/flame_creation.yml
  Resources/Prototypes/_CP14/Entities/Actions/Spells/Fire/tiefling_inner_fire.yml
  Resources/Prototypes/_CP14/Entities/Actions/Spells/Life/resurrection.yml
  Resources/Prototypes/_CP14/Entities/Actions/Spells/Life/sheep_polymorph.yml
  Resources/Prototypes/_CP14/Entities/Actions/Spells/Light/search_of_life.yml
  Resources/Prototypes/_CP14/Entities/Actions/Spells/Light/signal_light.yml
  Resources/Prototypes/_CP14/Entities/Actions/Spells/Lurker/Step.yml
  Resources/Prototypes/_CP14/Entities/Actions/Spells/Water/beer_creation.yml
  Resources/Prototypes/_CP14/Entities/Actions/Spells/Water/ice_arrow.yml
  Resources/Prototypes/_CP14/Entities/Actions/Spells/Water/water_creation.yml
Labels: enhancement, Minor

#5 Server Update From Parent
  Content.Server/Parallax/BiomeSystem.cs
  Content.Server/_CP14/RoundLeave/CP14RoundLeaveSystem.cs
  Resources/Locale/en-US/_CP14/lockKey/locks-types.ftl
  Resources/Locale/ru-RU/_CP14/lockKey/locks-types.ftl
  Resources/Maps/_CP14/comoss.yml
  Resources/Prototypes/_CP14/Entities/Actions/Spells/Life/cure_poison.yml
  Resources/Prototypes/_CP14/Entities/Actions/Spells/Light/search_of_life.yml
  Resources/Prototypes/_CP14/Entities/Actions/Spells/Water/water_creation.yml
  Resources/Prototypes/_CP14/Entities/Objects/Keys/Catalog/guard.yml
  Resources/Prototypes/_CP14/Entities/Objects/Keys/keyrings.yml
  Resources/Prototypes/_CP14/Entities/Structures/Decorations/flags_wallmount.yml
  Resources/Prototypes/_CP14/Entities/Structures/Doors/Locked/guard.yml
  Resources/Prototypes/_CP14/Entities/Structures/Specific/Demiplanes/round_end.yml
  Resources/Prototypes/_CP14/LockCategories/lockTypes.yml
  Resources/ServerInfo/_CP14/Guidebook_EN/JobsTabs/AdventurersTabs/Demiplanes.xml
  Resources/migration.yml
  signatures/version1/cla.json
Labels: Parent

#10 Parent Update
  Content.Client/_CP14/JoinQueue/QueueState.cs
  Content.Server/_CP14/DemiplaneTraveling/CP14StationDemiplaneMapSystem.cs
  Content.Shared/_CP14/Demiplane/Prototypes/CP14SpecialDemiplanePrototype.cs
  Content.Shared/_CP14/Workbench/Requirements/MaterialResource.cs
  Resources/ConfigPresets/_CP14/Dev.toml
  Resources/Locale/en-US/_CP14/discord/queue.ftl
  Resources/Locale/ru-RU/_CP14/discord/queue.ftl
  Resources/Prototypes/_CP14/Entities/Objects/Consumable/Smokeables/Pipes/pipe.yml
  Resources/Prototypes/_CP14/Procedural/Demiplane/Locations/cave_ice.yml
  Resources/Prototypes/_CP14/Procedural/Demiplane/Locations/cave_magma.yml
  Resources/Prototypes/_CP14/Procedural/Demiplane/Modifiers/Reward/rooms.yml
  Resources/Prototypes/_CP14/Sponsor/roles.yml
Labels: Parent

#11 Testing
  Content.Client/_CP14/JoinQueue/QueueState.cs
  Content.Server/_CP14/DemiplaneTraveling/CP14StationDemiplaneMapSystem.cs
  Content.Shared/_CP14/Demiplane/Prototypes/CP14SpecialDemiplanePrototype.cs
  Content.Shared/_CP14/Workbench/Requirements/MaterialResource.cs
  Resources/ConfigPresets/_CP14/Dev.toml
  Resources/Locale/en-US/_CP14/discord/queue.ftl
  Resources/Locale/ru-RU/_CP14/discord/queue.ftl
  Resources/Prototypes/_CP14/Entities/Objects/Consumable/Smokeables/Pipes/pipe.yml
  Resources/Prototypes/_CP14/Procedural/Demiplane/Locations/cave_ice.yml
  Resources/Prototypes/_CP14/Procedural/Demiplane/Locations/cave_magma.yml
  Resources/Prototypes/_CP14/Procedural/Demiplane/Modifiers/Reward/rooms.yml
  Resources/Prototypes/_CP14/Sponsor/roles.yml
Labels: Parent

#13 Testing
  Content.Server/_CP14/RoundEnd/CP14RoundEndSystem.CBT.cs
  README.md
  Resources/ConfigPresets/_CP14/Dev.toml
  Resources/Locale/ru-RU/_CP14/_PROTO/entities/entities.ftl
  Resources/Prototypes/_CP14/Entities/Mobs/NPC/myconide.yml
  Resources/Prototypes/_CP14/Entities/Objects/Specific/Farming/sack.yml
  Resources/Prototypes/_CP14/Entities/Objects/Specific/Farming/seeds.yml
  Resources/Prototypes/_CP14/Entities/Objects/Specific/Guard/GuardBell.yml
  Resources/Prototypes/_CP14/Entities/Structures/Doors/Locked/guildmaster.yml
  Resources/Prototypes/_CP14/Entities/Structures/Specific/Demiplanes/round_end.yml
  Resources/Prototypes/_CP14/Maps/Frigid_Coast.yml
  Resources/Prototypes/_CP14/Maps/comoss.yml
  Resources/Prototypes/_CP14/Recipes/Workbench/CookingTable/seeds.yml
  Resources/Prototypes/_CP14/Recipes/Workbench/sewing_table.yml
  Resources/Prototypes/_CP14/Roles/Jobs/Artisan/alchemist.yml
  Resources/Prototypes/_CP14/Roles/Jobs/Artisan/blacksmith.yml
  Resources/Prototypes/_CP14/Roles/Jobs/Mercenary/guildmaster.yml
  Resources/Prototypes/_CP14/Roles/Jobs/Traders/merchant.yml
  Resources/Prototypes/_CP14/tags.yml
  Resources/Textures/_CP14/Objects/Storage/sack.rsi/meta.json
  Resources/Textures/_CP14/Objects/Storage/sack.rsi/seed.png
  Tools/_CP14/LocalizationHelper/LocalizationHelper/entity.py
  Tools/_CP14/LocalizationHelper/LocalizationHelper/localization_helper.py
  Tools/_CP14/LocalizationHelper/LocalizationHelper/parsers/fluent/ftl_reader.py
  Tools/_CP14/LocalizationHelper/LocalizationHelper/prototype.py
  Tools/_CP14/LocalizationHelper/last_launch_result/result.json
  signatures/version1/cla.json
Labels: Parent

#24 Testing
  Resources/Prototypes/_CP14/Entities/Mobs/Species/HighElf.yml
Labels: bug, URGENT, Critical
